# Generated by Django 2.2.16 on 2021-12-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20211204_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавить картинки к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
